# Generated by Django 4.2.13 on 2024-05-18 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_alter_booking_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='routes',
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_due_customer',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='base_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_canceled',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_completed',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_locations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_identity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_driver_note',
            field=models.TextField(blank=True, default='None applicable', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='distance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_identity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='floors',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='helpers',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], default=1, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='loyal_customer_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='mid_month_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_option',
            field=models.CharField(blank=True, choices=[('EFT', 'EFT'), ('CASH', 'CASH')], default='CASH', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_size',
            field=models.FloatField(blank=True, choices=[(1.0, '1.0 Ton'), (1.5, '1.5 Ton'), (2.0, '2.0 Ton'), (4.0, '4.0 Ton'), (8.0, '8.0 Ton')], default=1.0, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
