# Generated by Django 4.2.13 on 2024-05-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_booking_routes_booking_amount_due_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='vehicle_size',
            new_name='vehicle_type',
        ),
    ]
