# Generated by Django 4.2.13 on 2024-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_rename_vehicle_size_booking_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_canceled',
            field=models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_completed',
            field=models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.FloatField(blank=True, choices=[(1.0, '1.0 Ton'), (1.5, '1.5 Ton'), (2.0, '2.0 Ton'), (3.0, '3.0 Ton'), (8.0, '8.0 Ton')], default=1.0, null=True),
        ),
    ]
