# Generated by Django 4.2.13 on 2024-05-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_booking_canceled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_locations',
            new_name='pickup_dropoff_locations',
        ),
    ]
