# Generated by Django 4.2.13 on 2024-05-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rename_booking_locations_booking_pickup_dropoff_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='pickup_dropoff_locations',
            new_name='pickup_dropoff_routes',
        ),
    ]
