# Generated by Django 4.2.14 on 2024-07-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_booking_cancelation_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_adjustment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
