# Generated by Django 4.2.14 on 2024-07-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_price_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_adjustment_note',
            field=models.CharField(blank=True, default='', max_length=1500, null=True),
        ),
    ]
