# Generated by Django 4.2.13 on 2024-06-07 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('surname', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('subject', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
