# Generated by Django 4.2.13 on 2024-06-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='responded',
            field=models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=False),
        ),
    ]
