# Generated by Django 4.2.13 on 2024-05-21 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPending',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('helpers', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], default=1, null=True)),
                ('floors', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=0, null=True)),
                ('payment_option', models.CharField(blank=True, choices=[('EFT', 'EFT'), ('CASH', 'CASH')], default='CASH', max_length=50, null=True)),
                ('customer_driver_note', models.TextField(blank=True, default='None applicable', max_length=1000, null=True)),
                ('vehicle_type', models.FloatField(blank=True, choices=[(1.0, '1.0 Ton'), (1.5, '1.5 Ton'), (2.0, '2.0 Ton'), (3.0, '3.0 Ton'), (8.0, '8.0 Ton')], default=1.0, null=True)),
                ('base_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount_due_customer', models.FloatField(blank=True, default=0.0, null=True)),
                ('mid_month_discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('distance', models.FloatField(blank=True, default=0.0, null=True)),
                ('loyal_customer_discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('pickup_dropoff_routes', models.JSONField(blank=True, default=list, null=True)),
                ('booking_completed', models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=False)),
                ('booking_canceled', models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=False)),
                ('booking_date', models.DateField(null=True)),
                ('booking_time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
