# Generated by Django 4.2.13 on 2024-05-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_corperate',
            field=models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_terms_cond_accept',
            field=models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(choices=[(False, 'NO'), (True, 'YES')], default=True),
        ),
    ]
